export const OTP_USER_REQUEST = 'OTP_USER_REQUEST'
export const OTP_USER_SUCCESS = 'OTP_USER_SUCCESS'
export const OTP_USER_FAILURE = 'OTP_USER_FALIURE'


export const OTP_FORGET_REQUEST = 'OTP_FORGET_REQUEST'
export const OTP_FORGET_SUCCESS = 'OTP_FORGET_SUCCESS'
export const OTP_FORGET_FAILURE = 'OTP_FORGET_FALIURE'